export { App } from './App';
export { Header } from './Header';
export { MainPage } from './MainPage';
export { Download } from './Download';
export { Features } from './Features';
export { Reviews } from './Reviews';
export { Prices } from './Prices';
export { Contacts } from './Contacts';
export { Footer } from './Footer';
